using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Atlas.Users.Domain.Entities.UserEntity;
using Atlas.Users.Infrastructure.Persistance.Entities;

namespace Atlas.Users.Infrastructure.Persistance;

public sealed class UsersDatabaseContext(DbContextOptions<UsersDatabaseContext> options) : IdentityDbContext<User, IdentityRole<Guid>, Guid>(options)
{
    /// <summary>
    /// Configures the model for the database context during the model creation process.
    /// </summary>
    /// <param name="modelBuilder">The builder used to construct the model for the database context.</param>
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        // Remove "AspNet" prefix from table names (auto-generated by AspNet Identity)
        foreach (var entity in modelBuilder.Model.GetEntityTypes())
            entity.SetTableName(entity.GetTableName()?.Replace("AspNet", ""));

        modelBuilder.ApplyConfigurationsFromAssembly(typeof(UsersDatabaseContext).Assembly);
    }

    /// <summary>
    /// Represents a collection of <see cref="User"/> in the context, or that can be queried from the database.
    /// </summary>
    public override DbSet<User> Users { get; set; }

    /// <summary>
    /// Represents a collection of <see cref="UsersOutboxMessage"/> in the context, or that can be queried from the database.
    /// </summary>
    public DbSet<UsersOutboxMessage> OutboxMessages { get; set; }

    /// <summary>
    /// Represents a collection of <see cref="UsersOutboxMessageConsumerAcknowledgement"/> in the context, or that can be queried from the database.
    /// </summary>
    public DbSet<UsersOutboxMessageConsumerAcknowledgement> OutboxMessageConsumerAcknowledgements { get; set; }
}