using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using Atlas.Users.Domain.Entities.UserEntity;
using Atlas.Shared.Infrastructure.Persistance;
using Atlas.Shared.Infrastructure.Persistance.Outbox;

namespace Atlas.Users.Infrastructure.Persistance;

public sealed class UsersDatabaseContext(DbContextOptions options) : IdentityDbContext<User, IdentityRole<Guid>, Guid>(options), IDatabaseContext
{
    /// <summary>
    /// Configures the model for the database context during the model creation process.
    /// </summary>
    /// <param name="modelBuilder">The builder used to construct the model for the database context.</param>
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        // Remove "AspNet" prefix from table names (auto-generated by AspNet Identity)
        foreach (var entity in modelBuilder.Model.GetEntityTypes())
            entity.SetTableName(entity.GetTableName()?.Replace("AspNet", ""));

        modelBuilder.ApplyConfigurationsFromAssembly(typeof(UsersDatabaseContext).Assembly);
    }

    /// <summary>
    /// Represents a collection of <see cref="User"/> in the context, or that can be queried from the database.
    /// </summary>
    public override DbSet<User> Users { get; set; }

    /// <summary>
    /// Represents a collection of <see cref="OutboxMessage"/> in the context, or that can be queried from the database.
    /// </summary>
    public DbSet<OutboxMessage> OutboxMessages { get; set; }

    /// <summary>
    /// Represents a collection of <see cref="OutboxMessageConsumerAcknowledgement"/> in the context, or that can be queried from the database.
    /// </summary>
    public DbSet<OutboxMessageConsumerAcknowledgement> OutboxMessageConsumerAcknowledgements { get; set; }
}