namespace Atlas.Users.Application;

/// <summary>
/// The types of tokens that can be generated by the <see cref="UserManager"/> class.
/// </summary>
internal static class UserToken
{
    /// <summary>
    /// Gets the name of the token type used to confirm a user's email address.
    /// </summary>
    public static string ConfirmUserEmail => "ConfirmUserEmail";

    /// <summary>
    /// Gets the name of the token type used to reset a user's password.
    /// </summary>
    public static string ResetPassword => "ResetPassword";

    /// <summary>
    /// Gets the name of the token type used to sign in a user.
    /// </summary>
    public static string SignIn => "SignIn";
}
